import './globals.css'
import { Inter } from 'next/font/google'
import AppBar from "@/components/AppBar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
	title: "Center Schools",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AppBar />
				{children}
			</body>
		</html>
	);
}
